version: '3.6'
services:
  hasura-backend-plus:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file: '.env.test'
    depends_on:
      - 'mailhog'
    environment:
      NODE_ENV: test
      JWT_ALGORITHM: HS256
      JWT_KEY: '${JWT_KEY}'
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_SECURE: 'false'
    volumes:
      - .:/app
      - /app/node_modules
      - ./test-mocks/migrations/1585679214182_custom_user_column:/app/migrations/1585679214182_custom_user_column
  graphql-engine:
    environment:
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "${JWT_KEY}"}'
  mailhog:
    image: mailhog/mailhog
