FROM alekzonder/puppeteer:latest

# Install git so we can use Jest watch mode
USER root
RUN apt-get update && apt-get install -y git
USER pptruser

ARG NODE_ENV=development
ENV NODE_ENV $NODE_ENV
ENV PORT 3000

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

HEALTHCHECK --interval=5s --timeout=5s --retries=3 CMD wget localhost:${PORT}/healthz -q -O - > /dev/null 2>&1

CMD ["yarn", "run", "dev-container"]
