exports.USER_FIELDS = process.env.USER_FIELDS ? process.env.USER_FIELDS.split(',') : [];
exports.HASURA_GRAPHQL_ENDPOINT = process.env.HASURA_GRAPHQL_ENDPOINT || 'https://hasura.your-app.com/v1alpha1/graphql';
exports.HASURA_GRAPHQL_ACCESS_KEY = process.env.HASURA_GRAPHQL_ACCESS_KEY || 'hasura-access-key';
exports.HASURA_GRAPHQL_JWT_SECRET = process.env.HASURA_GRAPHQL_JWT_SECRET ? JSON.parse(process.env.HASURA_GRAPHQL_JWT_SECRET) : {'type':'HS256', 'key': '1D122358E08EC3A01FC13246983AF69634A6AF96D419C3C86D2D5414EE649E96'};
exports.S3_ACCESS_KEY_ID = process.env.S3_ACCESS_KEY_ID || 's3-access-key-id';
exports.S3_SECRET_ACCESS_KEY = process.env.S3_SECRET_ACCESS_KEY || 's3-secret-access-key';
exports.S3_ENDPOINT = process.env.S3_ENDPOINT || 's3-endpoint';
exports.S3_BUCKET = process.env.S3_BUCKET || 's3-bucketname';
exports.DOMAIN = process.env.DOMAIN || 'localhost'; // or your backend host. Ex: backend.your-app.com
