name: Check Pull Request
on:
  pull_request:
    branches: [v2]
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - '*.md'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Run Jest tests
        run: ./run_tests.sh
