name: Code coverage
on:
  push:
    branches: [v2]
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - '*.md'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Run test script
        run: ./run_tests.sh
      - name: Publish report to codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/clover.xml
